### ISSUE TITLE
あ

### ISSUE THREAD

**Issue by yuuokazaki** [yuuokazaki/portfolio-admin#10]
# WBSのスクショ

# 各タスクの未完了部分

<h3>フロントエンド</h3> 

　ログイン：繋ぎ込みのテストが残っています。mustなので、業後に終わらせます。
　登録編集：明日には終わりそうです。
　検索　　：繋ぎ込み着手しました。
　参照　　：繋ぎ込み中途中です。mustなので、業後に終わらせます。
　TOP　　：チャート終了と同時に終了
　チャート：終了(must)

<h3>バックエンド</h3>

2日分遅れている→グラフ参照とアカウント参照を同じ人のタスクにし効率化を図る。
　登録API　　　：
　検索API　　　：終了 (JDBC方式) 
　ログインAPI　：終了
　参照API　　　：終了(JDBC方式) 
　グラフ削除API：
　アカウント参照API：終了(JDBC方式) 

# 報告

**Comment by yurino-sakamoto** [comment]
ありがとう✨
